### ISSUE TITLE
[TODO] New features

### ISSUE THREAD

**Issue by melody-rs** [Speak2Erase/OneShot-Script-Wrapper#1]
In order of importance:
- [x] Figure out how to run a command when pulling commits
- [x] Figure out how to run a command when pushing commits
- [x] Add .rxdata unpacker to convert .rxdata files to json or a non-binary format
- [x] Add an .rxdata re-packer to convert json to rxdata
- [ ] Documentation
- [ ] Vscode debugger (Nothing special, just something that formats the code, compresses it, and the runs the game)
- [ ] Make a GUI for the packer/unpacker
